openapi: 3.2.0
x-sailpoint-api:
  version: v2025
  audience: external-public
info:
  title: Test API
  version: 1.0.0
paths:
  /test:
    get:
      summary: Test endpoint
      operationId: test
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./version-ref-isolation-other.yaml#/components/schemas/TestSchema"

