openapi: 3.1.0
info:
  title: Test File 2 Unique
  version: 1.0.0
paths:
  /test2:
    get:
      operationId: uniqueId2
      summary: Get test 2
      description: Second file with unique operationId
      responses:
        "200":
          description: OK

