openapi: 3.1.0
info:
  title: Test File 1
  version: 1.0.0
paths:
  /test1:
    get:
      operationId: duplicateId
      summary: Get test 1
      description: First file with operationId
      responses:
        "200":
          description: OK

