openapi: 3.1.0
info:
  title: Test File 2
  version: 1.0.0
paths:
  /test2:
    get:
      operationId: duplicateId
      summary: Get test 2
      description: Second file with duplicate operationId
      responses:
        "200":
          description: OK

