openapi: 3.1.0
info:
  title: Test File 1 Unique
  version: 1.0.0
paths:
  /test1:
    get:
      operationId: uniqueId1
      summary: Get test 1
      description: First file with unique operationId
      responses:
        "200":
          description: OK

