package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/LukasParke/gossip/protocol"
)

// LintReport is the structured output written by --report-json.
type LintReport struct {
	Workspace       string            `json:"workspace"`
	RepoRoot        string            `json:"repoRoot,omitempty"`
	GeneratedAt     string            `json:"generatedAt"`
	DiagnosticCount int               `json:"diagnosticCount"`
	Files           []fileDiagnostics `json:"files"`
	Counts          SeverityCounts    `json:"counts"`
	ByFile          map[string]int    `json:"byFile"`
	ByRule          map[string]int    `json:"byRule"`
	RuleDocs        map[string]string `json:"ruleDocs,omitempty"`
	FileDetails     []FileDetail      `json:"fileDetails"`
	Scope           *ScopeMetadata    `json:"scope,omitempty"`
}

// ScopeMetadata describes how the CI run selected files for analysis.
type ScopeMetadata struct {
	Mode              string `json:"mode,omitempty"`
	ChangedFileCount  int    `json:"changedFileCount,omitempty"`
	ImpactedFileCount int    `json:"impactedFileCount,omitempty"`
	AnalyzedFileCount int    `json:"analyzedFileCount,omitempty"`
	FallbackReason    string `json:"fallbackReason,omitempty"`
}

// SeverityCounts breaks down diagnostic counts by severity.
type SeverityCounts struct {
	Error   int `json:"error"`
	Warning int `json:"warning"`
	Info    int `json:"info"`
	Hint    int `json:"hint"`
}

// FileDetail provides per-file diagnostic breakdown for reports.
type FileDetail struct {
	Path     string `json:"path"`
	Count    int    `json:"count"`
	Errors   int    `json:"errors"`
	Warnings int    `json:"warnings"`
}

func buildLintReport(workspace, repoRoot string, allDiags []fileDiagnostics) *LintReport {
	report := &LintReport{
		Workspace:   workspace,
		RepoRoot:    repoRoot,
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Files:       allDiags,
		ByFile:      make(map[string]int),
		ByRule:      make(map[string]int),
		RuleDocs:    make(map[string]string),
	}

	// Use repo root for path display if available, otherwise fall back to workspace.
	relBase := repoRoot
	if relBase == "" {
		relBase = workspace
	}

	for _, fd := range allDiags {
		rel, err := filepath.Rel(relBase, fd.Path)
		if err != nil {
			rel = fd.Path
		}
		// JSON reports and tests use forward slashes regardless of host OS.
		rel = filepath.ToSlash(rel)
		report.ByFile[rel] = len(fd.Diagnostics)
		report.DiagnosticCount += len(fd.Diagnostics)

		detail := FileDetail{Path: rel, Count: len(fd.Diagnostics)}
		for _, d := range fd.Diagnostics {
			switch d.Severity {
			case protocol.SeverityError:
				report.Counts.Error++
				detail.Errors++
			case protocol.SeverityWarning:
				report.Counts.Warning++
				detail.Warnings++
			case protocol.SeverityInformation:
				report.Counts.Info++
			case protocol.SeverityHint:
				report.Counts.Hint++
			}
			code := ""
			if d.Code != nil {
				code = fmt.Sprintf("%v", d.Code)
			}
			if code != "" {
				report.ByRule[code]++
				if d.CodeDescription != nil && d.CodeDescription.Href != "" {
					report.RuleDocs[code] = string(d.CodeDescription.Href)
				}
			}
		}
		report.FileDetails = append(report.FileDetails, detail)
	}

	return report
}

func writeJSONReport(path string, report *LintReport) error {
	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal report: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0644)
}

func writeMDReport(path string, report *LintReport) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return writeMDReportTo(f, report)
}

func writeMDReportTo(w io.Writer, report *LintReport) error {
	var b strings.Builder

	b.WriteString("# Telescope report\n\n")
	b.WriteString("> Generated by Telescope CI (same engine as the VS Code language server).\n\n")

	// Summary table.
	other := report.Counts.Info + report.Counts.Hint
	b.WriteString("## Summary\n\n")
	b.WriteString("| Metric | Value |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString(fmt.Sprintf("| Workspace | `%s` |\n", report.Workspace))
	b.WriteString(fmt.Sprintf("| Generated | `%s` |\n", report.GeneratedAt))
	if report.Scope != nil {
		b.WriteString(fmt.Sprintf("| Scope | %s |\n", scopeModeLabel(report.Scope)))
		if report.Scope.Mode == reportScopeChanged || report.Scope.ChangedFileCount > 0 {
			b.WriteString(fmt.Sprintf("| Changed files | %d |\n", report.Scope.ChangedFileCount))
		}
		if report.Scope.Mode == reportScopeChanged {
			b.WriteString(fmt.Sprintf("| Impacted files | %d |\n", report.Scope.ImpactedFileCount))
		}
		if report.Scope.AnalyzedFileCount > 0 {
			b.WriteString(fmt.Sprintf("| Analyzed files | %d |\n", report.Scope.AnalyzedFileCount))
		}
		if report.Scope.FallbackReason != "" {
			b.WriteString(fmt.Sprintf("| Scope fallback | %s |\n", report.Scope.FallbackReason))
		}
	}
	b.WriteString(fmt.Sprintf("| Diagnostics | %d (errors: %d, warnings: %d, other: %d) |\n",
		report.DiagnosticCount, report.Counts.Error, report.Counts.Warning, other))
	b.WriteString(fmt.Sprintf("| Files with issues | %d |\n", len(report.FileDetails)))
	b.WriteString("\n")

	// Files table with errors/warnings breakdown and markdown links.
	if len(report.FileDetails) > 0 {
		b.WriteString("## Files\n\n")
		b.WriteString("| File | Count | Errors | Warnings |\n")
		b.WriteString("| --- | ---: | ---: | ---: |\n")

		sorted := make([]FileDetail, len(report.FileDetails))
		copy(sorted, report.FileDetails)
		sort.Slice(sorted, func(i, j int) bool {
			return sorted[i].Count > sorted[j].Count
		})
		for _, fd := range sorted {
			b.WriteString(fmt.Sprintf("| [%s](%s) | %d | %d | %d |\n",
				fd.Path, fd.Path, fd.Count, fd.Errors, fd.Warnings))
		}
		b.WriteString("\n")
	}

	// Per-rule summary.
	if len(report.ByRule) > 0 {
		b.WriteString("## Rules\n\n")
		b.WriteString("| Rule | Count |\n")
		b.WriteString("| --- | ---: |\n")

		type ruleCount struct {
			rule  string
			count int
		}
		var sortedRules []ruleCount
		for r, c := range report.ByRule {
			sortedRules = append(sortedRules, ruleCount{r, c})
		}
		sort.Slice(sortedRules, func(i, j int) bool {
			return sortedRules[i].count > sortedRules[j].count
		})
		for _, rc := range sortedRules {
			b.WriteString(fmt.Sprintf("| %s | %d |\n", markdownRuleRef(rc.rule, report.RuleDocs[rc.rule]), rc.count))
		}
		b.WriteString("\n")
	}

	// Diagnostics grouped by rule with severity breakdown.
	if report.DiagnosticCount > 0 {
		mdRelBase := report.RepoRoot
		if mdRelBase == "" {
			mdRelBase = report.Workspace
		}
		byRule := make(map[string][]diagEntry)
		for _, fd := range report.Files {
			rel, err := filepath.Rel(mdRelBase, fd.Path)
			if err != nil {
				rel = fd.Path
			}
			for _, d := range fd.Diagnostics {
				code := ""
				if d.Code != nil {
					code = fmt.Sprintf("%v", d.Code)
				}
				byRule[code] = append(byRule[code], diagEntry{
					file:     rel,
					line:     int(d.Range.Start.Line) + 1,
					severity: severityName(d.Severity),
					code:     code,
					message:  d.Message,
				})
			}
		}

		b.WriteString("## Diagnostics (by rule)\n\n")
		var codes []string
		for code := range byRule {
			codes = append(codes, code)
		}
		sort.Slice(codes, func(i, j int) bool {
			return len(byRule[codes[i]]) > len(byRule[codes[j]])
		})

		for _, code := range codes {
			entries := byRule[code]
			errors := 0
			warnings := 0
			for _, e := range entries {
				switch e.severity {
				case "error":
					errors++
				case "warning":
					warnings++
				}
			}

			b.WriteString(fmt.Sprintf("<details>\n<summary>%s — %d diagnostics (errors: %d, warnings: %d)</summary>\n\n",
				htmlRuleRef(code, report.RuleDocs[code]), len(entries), errors, warnings))
			b.WriteString("| Severity | File | Location | Message |\n")
			b.WriteString("| --- | --- | --- | --- |\n")
			for _, e := range entries {
				msg := strings.ReplaceAll(e.message, "|", "\\|")
				msg = strings.ReplaceAll(msg, "\n", " ")
				if e.code != "" {
					msg = fmt.Sprintf("`%s` %s", e.code, msg)
				}
				b.WriteString(fmt.Sprintf("| %s | [`%s`](%s) | [L%d](%s#L%d) | %s |\n",
					e.severity, e.file, e.file, e.line, e.file, e.line, msg))
			}
			b.WriteString("\n</details>\n\n")
		}
	}

	_, err := io.WriteString(w, b.String())
	return err
}

type diagEntry struct {
	file     string
	line     int
	severity string
	code     string
	message  string
}

func severityName(s protocol.DiagnosticSeverity) string {
	switch s {
	case protocol.SeverityError:
		return "error"
	case protocol.SeverityWarning:
		return "warning"
	case protocol.SeverityInformation:
		return "info"
	case protocol.SeverityHint:
		return "hint"
	default:
		return "unknown"
	}
}

func markdownRuleRef(code, href string) string {
	if code == "" {
		return "`(no rule)`"
	}
	if href == "" {
		return fmt.Sprintf("`%s`", code)
	}
	return fmt.Sprintf("[`%s`](%s)", code, href)
}

func htmlRuleRef(code, href string) string {
	if code == "" {
		return "<code>(no rule)</code>"
	}
	if href == "" {
		return fmt.Sprintf("<code>%s</code>", code)
	}
	return fmt.Sprintf("<a href=\"%s\"><code>%s</code></a>", href, code)
}
