// Auto-generated by the leak-guard regen tool. Do not edit by hand.
//
// This module is intentionally standalone and depends only on yaml.v3 so
// the public-repo CI never needs to fetch any upstream Go module to run the
// leak guard.

module leak-guard-check

go 1.22

require gopkg.in/yaml.v3 v3.0.1
