openapi: 3.1.0
info:
  title: Test JSON API
  version: 1.0.0
  description: |-
    This is a **markdown** description for the API.

    It has multiple paragraphs and supports:
    - Lists
    - **Bold text**
    - *Italic text*
paths:
  /users:
    get:
      operationId: getUsers
      summary: Get all users
      description: |-
        Returns a list of users.

        ## Response Format

        The response is a JSON array of user objects.
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserList"
    post:
      operationId: createUser
      summary: Create a user
      description: Creates a new user in the system.
      requestBody:
        description: User data to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "201":
          description: User created successfully
  /users/{id}:
    get:
      operationId: getUserById
      summary: Get user by ID
      description: |-
        Returns a single user by their ID.

        Special characters test: "quotes" and \backslash\ and	tabs.
      parameters:
        - name: id
          in: path
          required: true
          description: The user's unique identifier
          schema:
            type: string
      responses:
        "200":
          description: User found
        "404":
          description: User not found
components:
  schemas:
    User:
      type: object
      description: |-
        Represents a user in the system.

        ### Properties

        | Property | Type | Description |
        |----------|------|-------------|
        | id | string | Unique identifier |
        | name | string | User's full name |
      properties:
        id:
          type: string
          description: Unique identifier for the user
        name:
          type: string
          description: User's full name
        email:
          type: string
          format: email
          description: User's email address
      required:
        - id
        - name
    UserList:
      type: array
      description: A list of users
      items:
        $ref: "#/components/schemas/User"
    CreateUserRequest:
      type: object
      description: Request body for creating a new user
      properties:
        name:
          type: string
          description: The name of the user to create
        email:
          type: string
          format: email
          description: Email address for the new user
      required:
        - name
        - email
