/**
 * Central export point for all OpenAPI 3.x schema definitions.
 *
 * These schemas are built using Zod with .meta() and .describe()
 * for proper JSON Schema generation via z.toJSONSchema().
 *
 * Supports OpenAPI 3.0, 3.1, and 3.2 specifications with version-specific schemas.
 */

// =============================================================================
// Telescope Configuration Schema
// =============================================================================
export {
	type AdditionalValidationGroup,
	AdditionalValidationGroupSchema,
	type OpenAPIRuleConfig,
	OpenAPIRuleConfigSchema,
	type Severity,
	SeveritySchema,
	type TelescopeConfig,
	TelescopeConfigSchema,
} from "./config-schema.js";

// =============================================================================
// OpenAPI 3.0 Schemas
// =============================================================================
export {
	ArraySchema30,
	BooleanSchema30,
	type Callback30,
	Callback30Schema,
	type Components30,
	Components30Schema,
	// Types
	type Contact30,
	// Individual schemas
	Contact30Schema,
	type Discriminator30,
	Discriminator30Schema,
	type Encoding30,
	Encoding30Schema,
	type Example30,
	Example30Schema,
	type ExternalDocumentation30,
	ExternalDocumentation30Schema,
	FileRef30Schema,
	type Header30,
	Header30Schema,
	type Info30,
	Info30Schema,
	IntegerSchema30,
	InternalRef30Schema,
	type License30,
	License30Schema,
	type Link30,
	Link30Schema,
	type MediaType30,
	MediaType30Schema,
	NumberSchema30,
	type OAuthFlow30,
	OAuthFlow30Schema,
	type OAuthFlows30,
	OAuthFlows30Schema,
	ObjectSchema30,
	type OpenAPI30,
	OpenAPI30Schema,
	type Operation30,
	Operation30Schema,
	type Parameter30,
	Parameter30Schema,
	type PathItem30,
	PathItem30Schema,
	type Paths30,
	Paths30Schema,
	type Reference30,
	Reference30Schema,
	type RequestBody30,
	RequestBody30Schema,
	type Response30,
	Response30Schema,
	type Responses30,
	Responses30Schema,
	type SchemaObject30,
	SchemaObject30Schema,
	type SecurityRequirement30,
	SecurityRequirement30Schema,
	type SecurityScheme30,
	SecurityScheme30Schema,
	type Server30,
	Server30Schema,
	type ServerVariable30,
	ServerVariable30Schema,
	StringSchema30,
	type Tag30,
	Tag30Schema,
	UrlRef30Schema,
	type XML30,
	XML30Schema,
} from "./openapi-3.0-module.js";

// =============================================================================
// OpenAPI 3.1 Schemas
// =============================================================================
export {
	ArraySchema31,
	BooleanSchema31,
	type Callback31,
	Callback31Schema,
	type Components31,
	Components31Schema,
	// Types
	type Contact31,
	// Individual schemas
	Contact31Schema,
	type Discriminator31,
	Discriminator31Schema,
	type Encoding31,
	Encoding31Schema,
	type Example31,
	Example31Schema,
	type ExternalDocumentation31,
	ExternalDocumentation31Schema,
	FileRef31Schema,
	type Header31,
	Header31Schema,
	type Info31,
	Info31Schema,
	IntegerSchema31,
	InternalRef31Schema,
	type License31,
	License31Schema,
	type Link31,
	Link31Schema,
	type MediaType31,
	MediaType31Schema,
	NullSchema31,
	NumberSchema31,
	type OAuthFlow31,
	OAuthFlow31Schema,
	type OAuthFlows31,
	OAuthFlows31Schema,
	ObjectSchema31,
	type OpenAPI31,
	OpenAPI31Schema,
	type Operation31,
	Operation31Schema,
	type Parameter31,
	Parameter31Schema,
	type PathItem31,
	PathItem31Schema,
	type Paths31,
	Paths31Schema,
	type Reference31,
	Reference31Schema,
	type RequestBody31,
	RequestBody31Schema,
	type Response31,
	Response31Schema,
	type Responses31,
	Responses31Schema,
	type SchemaObject31,
	SchemaObject31Schema,
	type SecurityRequirement31,
	SecurityRequirement31Schema,
	type SecurityScheme31,
	SecurityScheme31Schema,
	type Server31,
	Server31Schema,
	type ServerVariable31,
	ServerVariable31Schema,
	StringSchema31,
	type Tag31,
	Tag31Schema,
	UrlRef31Schema,
	type XML31,
	XML31Schema,
} from "./openapi-3.1-module.js";

// =============================================================================
// OpenAPI 3.2 Schemas
// =============================================================================
export {
	ArraySchema32,
	BooleanSchema32,
	type Callback32,
	Callback32Schema,
	type Components32,
	Components32Schema,
	// Types
	type Contact32,
	// Individual schemas
	Contact32Schema,
	type Discriminator32,
	Discriminator32Schema,
	type Encoding32,
	Encoding32Schema,
	type Example32,
	Example32Schema,
	type ExternalDocumentation32,
	ExternalDocumentation32Schema,
	FileRef32Schema,
	type Header32,
	Header32Schema,
	type Info32,
	Info32Schema,
	IntegerSchema32,
	InternalRef32Schema,
	type License32,
	License32Schema,
	type Link32,
	Link32Schema,
	type MediaType32,
	MediaType32Schema,
	NullSchema32,
	NumberSchema32,
	type OAuthFlow32,
	OAuthFlow32Schema,
	type OAuthFlows32,
	OAuthFlows32Schema,
	ObjectSchema32,
	type OpenAPI32,
	OpenAPI32Schema,
	type Operation32,
	Operation32Schema,
	type Parameter32,
	Parameter32Schema,
	type PathItem32,
	PathItem32Schema,
	type Paths32,
	Paths32Schema,
	type Reference32,
	Reference32Schema,
	type RequestBody32,
	RequestBody32Schema,
	type Response32,
	Response32Schema,
	type Responses32,
	Responses32Schema,
	type SchemaObject32,
	SchemaObject32Schema,
	type SecurityRequirement32,
	SecurityRequirement32Schema,
	type SecurityScheme32,
	SecurityScheme32Schema,
	type Server32,
	Server32Schema,
	type ServerVariable32,
	ServerVariable32Schema,
	StringSchema32,
	type Tag32,
	Tag32Schema,
	UrlRef32Schema,
	type XML32,
	XML32Schema,
} from "./openapi-3.2-module.js";
// =============================================================================
// Base Schemas (shared primitives - Contact, License, etc.)
// =============================================================================
export {
	type Contact,
	ContactSchema,
	type ExternalDocumentation,
	ExternalDocumentationSchema,
	type FileRef,
	FileRefSchema,
	type InternalRef,
	InternalRefSchema,
	type License,
	LicenseSchema,
	type OAuthFlow,
	OAuthFlowSchema,
	type Reference,
	ReferenceSchema,
	type SecurityRequirement,
	SecurityRequirementSchema,
	type UrlRef,
	UrlRefSchema,
	type XML,
	XMLSchema,
} from "./openapi-base.js";
