openapi: 3.1.0
info:
  title: Standalone API
  version: 1.0.0
  description: A fully self-contained OpenAPI specification with all components inline
tags:
  - name: Pets
    description: Pet operations
  - name: Users
    description: User operations
paths:
  /pets:
    get:
      summary: List pets
      operationId: listPets
      tags:
        - Pets
      description: Retrieve a list of all pets from the store
      security:
        - userAuth: []
      parameters:
        - name: limit
          in: query
          description: Maximum number of items to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
          example: 20
        - name: offset
          in: query
          description: Number of items to skip
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
          example: 0
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "429":
          description: Too many requests
        "500":
          description: Internal server error
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the pet
          example: 12345
        name:
          type: string
          description: Name of the pet
          example: Fluffy
        tag:
          type: string
          description: Tag associated with the pet
          example: "dog"
  securitySchemes:
    userAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Read access
            write: Write access

