openapi: 3.1.0
x-sailpoint-api:
  version: v2
  audience: external-public
info:
  title: API v2
  version: 2.0.0
  description: API version 2 with external references - contains edge cases and warnings
tags:
  - name: Pets
    description: Pet operations
  - name: Users
    description: User operations
paths:
  /pets:
    $ref: "./v2/paths/pets.yaml"
  /users:
    $ref: "./v2/paths/users.yaml"
components:
  schemas:
    Pet:
      $ref: "./v2/schemas/Pet.yaml"
    User:
      $ref: "./v2/schemas/User.yaml"
  parameters:
    LimitParam:
      $ref: "./v2/components/parameters.yaml#/components/parameters/LimitParam"
  securitySchemes:
    userAuth:
      $ref: "./v2/security/schemes.yaml#/components/securitySchemes/userAuth"
