openapi: 3.1.0
x-sailpoint-api:
  version: v2025
  audience: external-public
info:
  title: Comprehensive Warning Test Cases
  version: 1.0.0
  description: All warning-level test cases consolidated into a single document
tags:
  - name: Authentication
  - name: Users
paths:
  # Operation Basic Fields - Warning (short description)
  /test/operation-basic-fields-short-description:
    get:
      operationId: testOperationBasicFieldsShortDescription
      summary: Get test
      description: Short
      tags:
        - Users
      responses:
        "200":
          description: OK

  # Operation Summary - Warning (exceeds 5 words)
  /test/operation-summary-warning:
    get:
      operationId: testOperationSummaryWarning
      summary: This is a very long summary that exceeds five words
      description: Operation with summary exceeding 5 words
      tags:
        - Users
      responses:
        "200":
          description: OK

  # Operation Tags - Warning (duplicate)
  /test/operation-tags-warning-duplicate:
    get:
      operationId: testOperationTagsWarningDuplicate
      summary: Get users
      description: Operation with duplicate tags
      tags:
        - Users
        - Users
      responses:
        "200":
          description: OK

  # Operation ID Format - Warning (non-standard verb)
  /test/operation-id-format-warning:
    get:
      operationId: fetchUser
      summary: Get user
      description: Operation with non-standard verb in operationId
      tags:
        - Users
      responses:
        "200":
          description: OK

components:
  securitySchemes:
    userAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Read access

