openapi: 3.1.0
info:
  title: Test
  version: 1.0.0
paths:
  /test1:
    get:
      operationId: uniqueId1
      responses:
        "200":
          description: OK
  /test2:
    get:
      operationId: uniqueId2
      responses:
        "200":
          description: OK
