openapi: 3.2.0
x-sailpoint-api:
  version: v2025
  audience: external-public
info:
  title: Pet Store API
  version: 1.0.0
  description: A sample API with only ASCII characters
tags:
  - name: pets
    description: Pets operations
paths: {}

