name: Benchmarks

on:
  push:
    branches: [main]
    paths:
      - "server/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod

      - name: Run benchmarks
        run: go test ./... -run='^$' -bench=. -benchmem -count=5 -timeout=30m | tee bench.txt
        working-directory: server

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: go
          output-file-path: server/bench.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: dev/bench
          comment-on-alert: true
          alert-threshold: "130%"
          fail-on-alert: false
