import * as fs from "node:fs";
import * as path from "node:path";
import { URI } from "vscode-uri";
import type { Diagnostic as EngineDiagnostic } from "../engine/index.js";
import type { LintRunResult } from "./lint.js";

export interface GitHubBlobContext {
	owner: string;
	repo: string;
	sha: string;
}

function findGitRoot(startDir: string): string | null {
	// Best-effort: walk up until we find a .git directory.
	let dir = startDir;
	for (let i = 0; i < 25; i++) {
		if (fs.existsSync(path.join(dir, ".git"))) return dir;
		const parent = path.dirname(dir);
		if (parent === dir) break;
		dir = parent;
	}
	return null;
}

function severityLabel(sev: number | undefined): string {
	if (sev === 1) return "error";
	if (sev === 2) return "warning";
	if (sev === 3) return "info";
	if (sev === 4) return "hint";
	return "unknown";
}

function diagLine(d: EngineDiagnostic): number {
	return (d.range?.start?.line ?? 0) + 1;
}

function diagCode(d: EngineDiagnostic): string {
	return d.code?.toString() ?? "unknown";
}

function escapeMd(s: string): string {
	// Minimal escaping for tables/text.
	return s.replace(/\r?\n/g, " ").replace(/\|/g, "\\|");
}

function escapeMdLinkText(s: string): string {
	// Link text is allowed to contain backticks, but pipes/newlines break tables.
	return escapeMd(s);
}

function uriToFsPath(uri: string): string | null {
	try {
		const parsed = URI.parse(uri);
		if (parsed.scheme === "file") return parsed.fsPath;
		return null;
	} catch {
		return null;
	}
}

function toRepoRelativePath(repoRoot: string, uri: string): string {
	const fsPath = uriToFsPath(uri);
	if (!fsPath) return uri;
	const rel = path.relative(repoRoot, fsPath);
	// Normalize for GitHub markdown links
	return rel.split(path.sep).join("/");
}

function githubBlobUrl(ctx: GitHubBlobContext, repoRelPath: string, anchor?: string): string {
	const cleanPath = repoRelPath.replace(/^\/+/, "");
	const cleanAnchor = anchor ? (anchor.startsWith("#") ? anchor : `#${anchor}`) : "";
	return `https://github.com/${ctx.owner}/${ctx.repo}/blob/${ctx.sha}/${cleanPath}${cleanAnchor}`;
}

function mdLink(text: string, url: string): string {
	return `[${escapeMdLinkText(text)}](${url})`;
}

function mdLinkToFile(
	repoRelPath: string,
	github?: GitHubBlobContext,
): string {
	if (github) {
		return mdLink(`\`${repoRelPath}\``, githubBlobUrl(github, repoRelPath));
	}
	// GitHub renders relative links within the repo context in artifacts/markdown files,
	// but in PR comments they can incorrectly resolve under `/pull/...`.
	return mdLink(repoRelPath, repoRelPath);
}

function diagRange(
	d: EngineDiagnostic,
): { startLine: number; endLine: number; anchor: string; label: string } {
	const startLine = Math.max(1, (d.range?.start?.line ?? 0) + 1);
	const endLine = Math.max(startLine, (d.range?.end?.line ?? d.range?.start?.line ?? 0) + 1);
	const label = endLine === startLine ? `L${startLine}` : `L${startLine}-L${endLine}`;
	const anchor = endLine === startLine ? `#L${startLine}` : `#L${startLine}-L${endLine}`;
	return { startLine, endLine, anchor, label };
}

export function writeMarkdownReport(
	result: LintRunResult,
	opts?: { github?: GitHubBlobContext; maxDiagnosticsPerRule?: number },
): string {
	const lines: string[] = [];
	const now = new Date().toISOString();
	const repoRoot = findGitRoot(result.workspacePath) ?? process.cwd();
	const github = opts?.github;

	lines.push("# Telescope report");
	lines.push("");
	lines.push("> Generated by Telescope CI (same engine as the VS Code language server).");
	lines.push("");

	lines.push("## Summary");
	lines.push("");
	lines.push("| Metric | Value |");
	lines.push("| --- | --- |");
	lines.push(`| Workspace | \`${escapeMd(result.workspaceFolderUri)}\` |`);
	lines.push(`| Generated | \`${now}\` |`);
	lines.push(`| Roots | ${result.roots.length} |`);
	lines.push(
		`| Diagnostics | ${result.diagnostics.length} (errors: ${result.counts.error}, warnings: ${result.counts.warning}, other: ${result.counts.notice}) |`,
	);
	lines.push(`| Project hash | \`${escapeMd(result.projectHash)}\` |`);
	lines.push("");

	// Per-file summary
	const byFile = new Map<string, EngineDiagnostic[]>();
	for (const d of result.diagnostics) {
		const arr = byFile.get(d.uri) ?? [];
		arr.push(d);
		byFile.set(d.uri, arr);
	}

	if (byFile.size > 0) {
		lines.push("## Files");
		lines.push("");
		lines.push("| File | Count | Errors | Warnings |");
		lines.push("| --- | ---: | ---: | ---: |");
		const rows = [...byFile.entries()].map(([uri, diags]) => {
			let e = 0;
			let w = 0;
			for (const d of diags) {
				if (d.severity === 1) e++;
				else if (d.severity === 2) w++;
			}
			return { uri, count: diags.length, e, w };
		});
		rows.sort((a, b) => b.count - a.count || a.uri.localeCompare(b.uri));
		for (const r of rows) {
			const repoRel = toRepoRelativePath(repoRoot, r.uri);
			lines.push(
				`| ${mdLinkToFile(repoRel, github)} | ${r.count} | ${r.e} | ${r.w} |`,
			);
		}
		lines.push("");
	}

	// Per-rule summary
	if (Object.keys(result.byCode).length > 0) {
		lines.push("## Rules");
		lines.push("");
		lines.push("| Rule | Count |");
		lines.push("| --- | ---: |");
		const rows = Object.entries(result.byCode).sort((a, b) => b[1] - a[1]);
		for (const [code, count] of rows) {
			lines.push(`| \`${code}\` | ${count} |`);
		}
		lines.push("");
	}

	// Diagnostics grouped by rule (keeps people in the same “mind space”).
	if (result.diagnostics.length > 0) {
		lines.push("## Diagnostics (by rule)");
		lines.push("");

		const byRule = new Map<string, EngineDiagnostic[]>();
		for (const d of result.diagnostics) {
			const code = diagCode(d);
			const arr = byRule.get(code) ?? [];
			arr.push(d);
			byRule.set(code, arr);
		}

		const ruleCodes = [...byRule.keys()].sort((a, b) => {
			const ac = byRule.get(a)?.length ?? 0;
			const bc = byRule.get(b)?.length ?? 0;
			return bc - ac || a.localeCompare(b);
		});

		for (const code of ruleCodes) {
			const allDiags = (byRule.get(code) ?? []).slice().sort((a, b) => {
				const aUri = toRepoRelativePath(repoRoot, a.uri);
				const bUri = toRepoRelativePath(repoRoot, b.uri);
				const aLine = a.range?.start?.line ?? 0;
				const bLine = b.range?.start?.line ?? 0;
				const aChar = a.range?.start?.character ?? 0;
				const bChar = b.range?.start?.character ?? 0;
				return aUri.localeCompare(bUri) || aLine - bLine || aChar - bChar;
			});

			let e = 0;
			let w = 0;
			for (const d of allDiags) {
				if (d.severity === 1) e++;
				else if (d.severity === 2) w++;
			}

			const maxPerRule = opts?.maxDiagnosticsPerRule;
			const diags =
				typeof maxPerRule === "number" && Number.isFinite(maxPerRule) && maxPerRule > 0
					? allDiags.slice(0, maxPerRule)
					: allDiags;

			lines.push("<details>");
			lines.push(
				`<summary><code>${escapeMd(code)}</code> — ${allDiags.length} diagnostics (errors: ${e}, warnings: ${w})</summary>`,
			);
			lines.push("");
			lines.push("| Severity | File | Location | Message |");
			lines.push("| --- | --- | --- | --- |");

			for (const d of diags) {
				const repoRel = toRepoRelativePath(repoRoot, d.uri);
				const r = diagRange(d);
				const fileUrl = github ? githubBlobUrl(github, repoRel) : repoRel;
				const locUrl = github ? githubBlobUrl(github, repoRel, r.anchor) : `${repoRel}${r.anchor}`;
				lines.push(
					`| ${severityLabel(d.severity)} | ${mdLink(
						`\`${repoRel}\``,
						fileUrl,
					)} | ${mdLink(r.label, locUrl)} | ${escapeMd(d.message ?? "")} |`,
				);
			}

			lines.push("");
			if (diags.length < allDiags.length) {
				lines.push(
					`_Showing ${diags.length} of ${allDiags.length} diagnostics for this rule. See the workflow artifact for the full list._`,
				);
				lines.push("");
			}
			lines.push("</details>");
			lines.push("");
		}
	}

	return `${lines.join("\n")}\n`;
}

export async function writeJsonReport(
	path: string,
	result: LintRunResult,
): Promise<void> {
	const { writeFile } = await import("node:fs/promises");
	const payload = {
		workspace: result.workspaceFolderUri,
		roots: result.roots,
		diagnosticCount: result.diagnostics.length,
		diagnostics: result.diagnostics,
		counts: result.counts,
		byUri: result.byUri,
		byCode: result.byCode,
		projectHash: result.projectHash,
	};
	await writeFile(path, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
}


